version: 



services:

    nginx: nginx

    container_name: nginx

    ports:
    
        -"80:80"

    mysql:
        
        image: mysql

        container_name: mysql

        ports:

            -"3306:3306"

        networks: 

            - b0

        environment:

            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

networks:

    b0: 

        external: true