version:




services:

	nginx:
		image: nginx

		container-name: nginx

		ports:

			-"80:80"


	mysql:
		image:mysql

		container-name: mysql

		ports:
			- "3306:3306"

		environment: 
			MYSQL_ROOT_PASSWORD: root

